# Five Torch Function which you don't even Know

### These function might come handy to you as per need. We will have slight inside with each functions


The following function i will discuss in these.
For any futher query you can either contact ping me or goto Pytorch Documentation.

- expand(*sizes) → Tensor
- torch.mean()
- is_leaf
- torch.squeeze(input, dim=None, out=None)
- torch.reshape(input, shape)

In [1]:
# Import torch and other required modules
import torch

## expand(*sizes)
Returns a new view of the self tensor with singleton dimensions expanded to a larger size.

In [4]:
x = torch.tensor([[1], [2], [3]])
x

tensor([[1],
        [2],
        [3]])

In [8]:
x.size() # to check the size of the tensor


torch.Size([3, 1])

In [16]:

x.expand(4,1)

RuntimeError: The expanded size of the tensor (4) must match the existing size (3) at non-singleton dimension 0.  Target sizes: [4, 1].  Tensor sizes: [3, 1]

you can can't give it value like . It must match the exisiting size in non-singleton dimension as in above case (3,-1) or (3,5)

In [17]:
x.expand(3, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [18]:
x.expand(-1, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

So in above example we show how we can expend the given tensor into new dimension if you don't want to create random value you can just expend those value which are already in tensor 

is good to use this when you need to have new dimension tensor of same data

it can be useful in case of padding in sliding window in image classification 

## torch.mean()

it give the mean of all the tensor

- torch.mean(input, dim, keepdim=False, out=None) → Tensor

- input (Tensor) – the input tensor.

- dim (int or tuple of python:ints) – the dimension or dimensions to reduce.

- keepdim (bool) – whether the output tensor has dim retained or not.

- out (Tensor, optional) – the output tensor.

In [20]:
a = torch.randn(4, 4)
a

tensor([[ 0.3885, -0.7974,  0.3446,  1.4624],
        [ 0.9686, -0.6411, -1.7166, -0.0583],
        [ 0.6171,  1.5840,  0.6742,  0.7742],
        [-0.6788, -0.3683,  0.0303, -0.9193]])

example tensor we create with randn

In [21]:
torch.mean(a)

tensor(0.1040)

so it gives us the mean of all the values in the tensor 

In [22]:
torch.mean(a, 1)

tensor([ 0.3495, -0.3619,  0.9124, -0.4840])

to calculate coloumn by

In [24]:
torch.mean(a, 1, True)

tensor([[ 0.3495],
        [-0.3619],
        [ 0.9124],
        [-0.4840]])

to keep the dimension 

when we need the mean in different style we can use this 

##  is_leaf

All Tensors that have requires_grad which is False will be leaf Tensors by convention.

it is use to check the value grad can be calculated if we used requires_grad True or not 

In [25]:
a = torch.rand(10, requires_grad=True)

random init

In [26]:
a.is_leaf

True

we in initial set the requires_grad=True so if we wanna check it possible to calculate it's grad

In [46]:
c = torch.rand(10, requires_grad=True) + 2

In [47]:
c.is_leaf

False

in above case its not possible 

## torch.reshape()

Returns a tensor with the same data and number of elements as input, but with the specified shape.

In [29]:
a = torch.arange(4.)

random initialize values 

In [30]:
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

to reshape another dimensions

In [31]:
b = torch.tensor([[0, 1], [2, 3]])

In [32]:
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

its very useful throughout in learning wherever we need to match the dimensions

## torch.squeeze()

Returns a tensor with all the dimensions of input of size 1 removed.

For example, if input is of shape:(A×1×B×C×1×D) then the out tensor will be of shape: (A×B×C×D) .
When dim is given, a squeeze operation is done only in the given dimension

In [33]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [34]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

it removes the 1 from the dimension and squeeze the tensor

In [35]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [36]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

we can specify which dimension we want to squeeze

this is useful where we need to from some dimension from our tensor 

## Conclusion

- Try all these above function by forking this notebook and explore them.
- They can be useful for you in different way.
- Let me know if you find anything interesting.
- There are so many function we can't go through in single day. We might encounter them as we go so keep learning
- So get your hands dirty in Pytorch.


Suggestions are welcome 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [40]:
!pip install jovian --upgrade --quiet

In [41]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
